DROP TABLE IF EXISTS "StrategyPosition" CASCADE;
DROP TABLE IF EXISTS "StrategyLog" CASCADE;
DROP TABLE IF EXISTS "Strategy" CASCADE;
DROP TABLE IF EXISTS "ProfitShare" CASCADE;

ALTER TABLE "Order" DROP COLUMN IF EXISTS "strategyId";

DROP TYPE IF EXISTS "StrategyStatus";
